// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NcI_1NZ7h6YuiwIc_h5AEXifa8VlOdw',
    appId: '1:655195445652:web:34b7ba4d4173c7f4b09781',
    messagingSenderId: '655195445652',
    projectId: 'xasusqore-9e6d0',
    authDomain: 'xasusqore-9e6d0.firebaseapp.com',
    storageBucket: 'xasusqore-9e6d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1jIUpoVX5-29HS9wPv2-yvvPFWFh8fuM',
    appId: '1:655195445652:android:e5e3e3b552da25c7b09781',
    messagingSenderId: '655195445652',
    projectId: 'xasusqore-9e6d0',
    storageBucket: 'xasusqore-9e6d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuL6IMMDlDoQwcc89LRvNb-_9j7ESnNis',
    appId: '1:655195445652:ios:8c82aba2d9947b80b09781',
    messagingSenderId: '655195445652',
    projectId: 'xasusqore-9e6d0',
    storageBucket: 'xasusqore-9e6d0.appspot.com',
    iosBundleId: 'com.example.xasusQore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuL6IMMDlDoQwcc89LRvNb-_9j7ESnNis',
    appId: '1:655195445652:ios:8c82aba2d9947b80b09781',
    messagingSenderId: '655195445652',
    projectId: 'xasusqore-9e6d0',
    storageBucket: 'xasusqore-9e6d0.appspot.com',
    iosBundleId: 'com.example.xasusQore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3NcI_1NZ7h6YuiwIc_h5AEXifa8VlOdw',
    appId: '1:655195445652:web:923e9c5bf0760e3eb09781',
    messagingSenderId: '655195445652',
    projectId: 'xasusqore-9e6d0',
    authDomain: 'xasusqore-9e6d0.firebaseapp.com',
    storageBucket: 'xasusqore-9e6d0.appspot.com',
  );
}
